name: zenFilter
description: A Flutter app for content filtering and settings.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.4+6
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  get: ^4.6.6
  url_launcher: ^6.2.2
  installed_apps: ^1.3.1
  flutter_inappwebview: ^6.0.0
  app_settings: ^5.1.1
  device_apps: ^2.2.0
  lottie: ^3.1.0
  intl: ^0.19.0
  html: ^0.15.0
  permission_handler: ^11.3.0
  usage_stats: ^1.2.0
  flutter_switch: ^0.3.2
  change_app_package_name: ^1.1.0
  file: ^7.0.0
  flutter_launcher_icons: "^0.13.1"
  curved_navigation_bar: ^1.0.3
  flutter_slider_drawer: ^2.1.3
  syncfusion_flutter_charts: ^25.1.35
  fl_chart: ^0.66.2
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  babstrap_settings_screen: ^0.1.6
  flutter_settings_screen_ex: ^0.0.1+5
  image_picker: ^1.0.4
  flutter_dotenv: ^5.1.0
  web_browser: ^0.5.0
  share: ^2.0.4
  connectivity_plus: ^5.0.2
  flutter_spinkit: ^5.2.0
  flutter_nude_checker: ^1.0.0
  contactus: ^1.2.3
  app_usage: ^3.0.1
  package_info_plus: ^5.0.1
  mailto: ^2.0.0
  appcheck: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_icons:
  image_path: "assets/images/appLogo.png" 
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/images/
    - assets/jsonFiles/
    - assets/animationAsset/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
